# Generated by Django 3.2 on 2023-06-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue_tree_api', '0003_auto_20230628_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='typegroup',
            name='type_group_people_max',
            field=models.IntegerField(null=True),
        ),
    ]
