# Generated by Django 3.2 on 2023-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue_tree_api', '0005_auto_20230629_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typegroup',
            name='type_group_detail',
        ),
        migrations.AddField(
            model_name='typegroup',
            name='type_group_detail_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='typegroup',
            name='type_group_detail_th',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
