# Generated by Django 2.2 on 2023-06-27 03:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('channel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_type_name', models.CharField(max_length=55)),
                ('channel_code', models.CharField(max_length=10)),
                ('channel_status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'chnnel_type',
            },
        ),
        migrations.CreateModel(
            name='FillList',
            fields=[
                ('fill_id', models.AutoField(primary_key=True, serialize=False)),
                ('fill_name', models.CharField(blank=True, max_length=55, null=True)),
                ('fill_type', models.CharField(blank=True, max_length=55, null=True)),
                ('fill_status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'fill_list',
            },
        ),
        migrations.CreateModel(
            name='SubFillList',
            fields=[
                ('sub_fill_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_fill_name', models.CharField(blank=True, max_length=55, null=True)),
                ('sub_fill_status', models.IntegerField(default=1)),
                ('sub_fill_description', models.CharField(max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('sub_fill_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_fill_list_id', to='blue_tree_bof.FillList')),
            ],
            options={
                'db_table': 'sub_fill_list',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_booking_id', models.CharField(blank=True, max_length=55)),
                ('order_id_order_agent', models.CharField(blank=True, max_length=55)),
                ('order_agent_name', models.CharField(blank=True, max_length=100)),
                ('order_booking_date', models.DateField(blank=True)),
                ('order_use_date', models.DateField(blank=True)),
                ('order_customer_name', models.CharField(blank=True, max_length=100)),
                ('order_mobile_phone', models.CharField(max_length=10)),
                ('order_email', models.CharField(blank=True, max_length=100, null=True)),
                ('order_number_of_people', models.IntegerField()),
                ('order_credit_term', models.IntegerField()),
                ('order_status', models.IntegerField(default=0)),
                ('order_status_policy', models.BooleanField(default=False)),
                ('order_payment_slip', models.ImageField(blank=True, default='payment/slip/no_slip.png', null=True, upload_to='payment/slip/')),
                ('order_customer_fill', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('order_channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_channel_id', to='blue_tree_bof.ChannelType')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
