# Generated by Django 3.2 on 2023-07-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blue_tree_bof', '0002_auto_20230627_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerApp',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name_th', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_description_th', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_image', models.ImageField(blank=True, default='img/none/no_banner.png', null=True, upload_to='img/banner')),
                ('banner_status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'banner_app',
            },
        ),
        migrations.CreateModel(
            name='HappeningApp',
            fields=[
                ('happening_id', models.AutoField(primary_key=True, serialize=False)),
                ('happening_name_th', models.CharField(blank=True, max_length=255, null=True)),
                ('happening_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('happening_description_th', models.CharField(blank=True, max_length=255, null=True)),
                ('happening_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('happening_discount_price', models.FloatField(default=0)),
                ('happening_status', models.IntegerField(default=1)),
                ('happening_product', models.IntegerField(null=True)),
                ('happening_image', models.ImageField(blank=True, default='img/none/no_img.png', null=True, upload_to='img/happening')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'happening_app',
            },
        ),
        migrations.CreateModel(
            name='PromotionApp',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion_name_th', models.CharField(blank=True, max_length=255, null=True)),
                ('promotion_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('promotion_description_th', models.CharField(blank=True, max_length=255, null=True)),
                ('promotion_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('promotion_discount_price', models.FloatField(default=0)),
                ('promotion_maximum_discount', models.IntegerField(default=0)),
                ('promotion_status', models.IntegerField(default=1)),
                ('promotion_image', models.ImageField(blank=True, default='img/none/no_img.png', null=True, upload_to='img/promotion')),
                ('promotion_date_start', models.DateTimeField(blank=True, null=True)),
                ('promotion_date_end', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promotion_app',
            },
        ),
        migrations.CreateModel(
            name='ServiceApp',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name_th', models.CharField(blank=True, max_length=150, null=True)),
                ('service_name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('service_description_th', models.CharField(blank=True, max_length=150, null=True)),
                ('service_description_en', models.CharField(blank=True, max_length=150, null=True)),
                ('service_link', models.CharField(max_length=255, null=True)),
                ('service_status', models.IntegerField(default=1)),
                ('service_icon', models.ImageField(blank=True, default='img/none/no_icon.png', null=True, upload_to='img/service')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_app',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_verify', models.IntegerField(default=0)),
                ('users_status', models.IntegerField(default=0)),
                ('users_first_name', models.CharField(max_length=150, null=True)),
                ('users_last_name', models.CharField(max_length=150, null=True)),
                ('users_email', models.CharField(max_length=100, null=True)),
                ('users_password', models.CharField(max_length=200)),
                ('users_tel', models.IntegerField(max_length=12, null=True)),
                ('users_image', models.ImageField(blank=True, default='img/none/no_img.png', null=True, upload_to='img/users/')),
                ('users_rank', models.IntegerField(default=0)),
                ('users_point', models.IntegerField(default=0)),
                ('users_role', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('udpate_at', models.DateTimeField(auto_now=True)),
                ('users_activate_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UsersToken',
            fields=[
                ('users_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_token_key', models.CharField(blank=True, max_length=255)),
                ('users_token_status', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('users_token_users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_token_users_id', to='blue_tree_bof.users')),
            ],
            options={
                'db_table': 'users_token',
            },
        ),
    ]
