# Generated by Django 3.2 on 2023-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue_tree_bof', '0003_bannerapp_happeningapp_promotionapp_serviceapp_users_userstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='udpate_at',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='users',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userstoken',
            name='users_token_status',
            field=models.IntegerField(default=1),
        ),
    ]
