# Generated by Django 3.2 on 2023-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue_tree_bof', '0004_auto_20230713_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationApp',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_name_th', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_description_th', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_status', models.IntegerField(default=1)),
                ('notification_image', models.ImageField(blank=True, default='img/none/no_img.png', null=True, upload_to='img/notification')),
                ('notification_date_start', models.DateTimeField(blank=True, null=True)),
                ('notification_date_end', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_app',
            },
        ),
    ]
