# Generated by Django 3.2 on 2023-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue_tree_bof', '0005_notificationapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoken',
            name='users_token_refresh',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
